# Generated by Django 6.0.4 on 2026-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_topic_owner_alter_entry_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Announcement')),
                ('is_active', models.BooleanField(default=False, verbose_name='Display?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
